services:
  regression:
    image: selenium-pytest
    container_name: uiautomation_container
    build:
      context: .
    volumes:
      - ./:/usr/workspace
    command: bash -c "ls -la && pytest -sv --alluredir=allure-results"
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}