services:
  regression:
    image: selenium-pytest
    container_name: uiautomation_container
    build:
      context: .
    volumes:
      - ./:/usr/workspace
    #    command: bash -c "ls -la && pytest -sv --alluredir=allure-results main.py"
    command: bash -c "ls -la && pytest -vs --alluredir=allure-results tests/login_test.py::TestLogin::test_successful_login"
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}